---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: lab-apps-public
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://github.com/ksvijayb/homelab-charts.git
  ref:
    branch: master
  secretRef:
    name: flux-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  url: https://charts.bitnami.com/bitnami
